"""Tests for the REAL external transparency-log anchor (U51 external anchor).

These prove the external anchor is fail-closed WITHOUT touching the live HC-01
chain: a published notary root is committed to a log keyed by an EXTERNAL public
key (pinned out-of-band, never runtime-generated by the audit process) using RFC
6962 Merkle inclusion proofs + a signed tree head. An auditor verifies against
the pinned external key without trusting the operator. The LocalReferenceLog is an
in-process stand-in for a real third-party log (its key is supplied out-of-band
and pinned, not runtime-random).
"""
from __future__ import annotations

import json
import tempfile

import pytest

from src.kernels.audit.dual_signature import (
    DEFAULT_SIGN_ALG,
    SIGN_ALGORITHMS,
)
from src.kernels.audit.external_anchor import (
    ExternalAnchorReceipt,
    ExternalTransparencyAnchor,
    LocalReferenceLog,
    SignedTreeHead,
    merkle_inclusion_proof,
    merkle_root,
    verify_inclusion_proof,
)
from src.kernels.audit.inclusion_proof import ChainHeadNotary, head_digest_of
from src.kernels.audit.root_of_trust import ChainRootOfTrust, generate_keypair


def _ref_keypair():
    return SIGN_ALGORITHMS[DEFAULT_SIGN_ALG].generate_keypair()


def _ref_log():
    priv, pub = _ref_keypair()
    return LocalReferenceLog(log_priv=priv, log_pub=pub), pub


# --- RFC 6962 Merkle math (pure, no transport) ----------------------------- #
def test_rfc6962_root_deterministic_and_order_sensitive():
    a, b, c = b"aaa", b"bbb", b"ccc"
    r1 = merkle_root([a, b, c])
    r2 = merkle_root([a, b, c])
    r3 = merkle_root([a, c, b])
    assert r1 == r2
    assert r1 != r3


def test_rfc6962_inclusion_proof_round_trip_all_indices():
    leaves = [bytes([i]) * 5 for i in range(7)]
    root = merkle_root(leaves)
    for i in range(7):
        proof = merkle_inclusion_proof(leaves, i)
        ok, _ = verify_inclusion_proof(leaves[i], i, proof, 7, root)
        assert ok, "index %d failed" % i


def test_rfc6962_tampered_leaf_rejected():
    leaves = [b"x", b"y", b"z"]
    root = merkle_root(leaves)
    proof = merkle_inclusion_proof(leaves, 0)
    ok, _ = verify_inclusion_proof(b"X", 0, proof, 3, root)
    assert not ok


def test_rfc6962_wrong_root_rejected():
    leaves = [b"x", b"y", b"z"]
    proof = merkle_inclusion_proof(leaves, 1)
    ok, _ = verify_inclusion_proof(leaves[1], 1, proof, 3, b"\x00" * 32)
    assert not ok


# --- External anchor end-to-end (pinned out-of-band key) ------------------- #
def test_external_anchor_publish_and_verify_round_trip():
    log, pub = _ref_log()
    anchor = ExternalTransparencyAnchor(external_pub_pem=pub, transport=log, self_attested=True)
    receipt = anchor.publish("de" * 32)
    ok, reason = anchor.verify_receipt(receipt, "de" * 32)
    assert ok, reason
    assert anchor.anchored_roots == ["de" * 32]


def test_external_anchor_tampered_root_rejected():
    log, pub = _ref_log()
    anchor = ExternalTransparencyAnchor(external_pub_pem=pub, transport=log, self_attested=True)
    receipt = anchor.publish("ab" * 32)
    ok, _ = anchor.verify_receipt(receipt, "cd" * 32)
    assert not ok


def test_external_anchor_forged_sth_signature_rejected():
    log, pub = _ref_log()
    anchor = ExternalTransparencyAnchor(external_pub_pem=pub, transport=log, self_attested=True)
    receipt = anchor.publish("ab" * 32)
    # Mutate the STH signature so it no longer verifies against the pinned key.
    forged = ExternalAnchorReceipt(
        index=receipt.index,
        proof=receipt.proof,
        sth=SignedTreeHead(
            tree_size=receipt.sth.tree_size,
            root_hash=receipt.sth.root_hash,
            timestamp=receipt.sth.timestamp,
            sig_alg=receipt.sth.sig_alg,
            key_id=receipt.sth.key_id,
            signature="A" + receipt.sth.signature[1:],
        ),
        self_attested=receipt.self_attested,
    )
    ok, reason = anchor.verify_receipt(forged, "ab" * 32)
    assert not ok
    assert "STH" in reason


def test_external_anchor_requires_pinned_external_key():
    log, _ = _ref_log()
    with pytest.raises(ValueError):
        ExternalTransparencyAnchor(external_pub_pem=None, transport=log)


def test_external_anchor_reports_self_attested_honestly():
    log, pub = _ref_log()
    anchor = ExternalTransparencyAnchor(external_pub_pem=pub, transport=log, self_attested=True)
    assert anchor.independent is False
    receipt = anchor.publish("ab" * 32)
    ok, reason = anchor.verify_receipt(receipt, "ab" * 32)
    assert ok
    assert "SELF-ATTESTED" in reason


def test_external_anchor_save_load_round_trip():
    log, pub = _ref_log()
    anchor = ExternalTransparencyAnchor(external_pub_pem=pub, transport=log, self_attested=True)
    anchor.publish("aa" * 32)
    anchor.publish("bb" * 32)
    with tempfile.NamedTemporaryFile(mode="w", suffix=".jsonl", delete=False) as fh:
        path = fh.name
    anchor.save(path)
    loaded = ExternalTransparencyAnchor.load(
        path, external_pub_pem=pub, transport=log, self_attested=True
    )
    assert loaded.anchored_roots == ["aa" * 32, "bb" * 32]
    ok, _ = loaded.verify_consistency()
    assert ok


def test_external_anchor_load_refuses_tampered_file():
    log, pub = _ref_log()
    anchor = ExternalTransparencyAnchor(external_pub_pem=pub, transport=log, self_attested=True)
    anchor.publish("aa" * 32)
    anchor.publish("bb" * 32)
    with tempfile.NamedTemporaryFile(mode="w", suffix=".jsonl", delete=False) as fh:
        path = fh.name
    anchor.save(path)
    # Flip the first anchored root string in the file.
    with open(path, "r", encoding="utf-8") as fh:
        lines = fh.readlines()
    obj = json.loads(lines[0])
    obj["root"] = "zz" * 32
    lines[0] = json.dumps(obj) + "\n"
    with open(path, "w", encoding="utf-8") as fh:
        fh.writelines(lines)
    with pytest.raises(ValueError):
        ExternalTransparencyAnchor.load(
            path, external_pub_pem=pub, transport=log, self_attested=True
        )


def test_external_anchor_composes_with_u51_notary():
    kp = generate_keypair()
    rot = ChainRootOfTrust(private_pem=kp.private_pem, public_pem=kp.public_pem)
    notary = ChainHeadNotary(checkpoint_interval=3)
    for seq in range(5):
        att = rot.sign_head(seq=seq, head_hash="h" * 64, link_hash="l" * 64)
        notary.append_head(head_digest_of(att))
    root = notary.publish_root()
    log, pub = _ref_log()
    anchor = ExternalTransparencyAnchor(external_pub_pem=pub, transport=log, self_attested=True)
    receipt = anchor.publish(root.root_hash)
    ok, reason = anchor.verify_receipt(receipt, root.root_hash)
    assert ok, reason
    # Tampered notary root must not verify against the receipt.
    ok, _ = anchor.verify_receipt(receipt, "c" * 64)
    assert not ok
