"""
Observability module for LiuHao AI OS.
"""

from .logging_utils import (
    get_correlation_id,
    set_correlation_id,
    correlation_context,
    request_context,
    configure_logging,
    get_logger,
    get_structured_logger,
    log_ai_request,
    log_ai_response,
    log_agent_task,
    log_goal_decomposition,
)

from .metrics import (
    REGISTRY,
    get_metrics_registry,
    generate_metrics,
    track_http_request,
    track_provider_request,
    track_provider_error,
    set_provider_availability,
    track_agent_task,
    track_coordination,
    track_goal_decomposition,
    track_task_execution,
    set_queue_depth,
    set_employee_agents,
    set_employee_success_rate,
    TrackProviderRequest,
    TrackAgentTask,
    TrackGoalDecomposition,
    # Metric objects
    http_requests_total,
    http_request_duration_seconds,
    provider_requests_total,
    provider_request_duration_seconds,
    provider_tokens_total,
    provider_errors_total,
    provider_up,
    provider_active_requests,
    agent_tasks_total,
    agent_task_duration_seconds,
    agent_coordination_total,
    agent_coordination_failures_total,
    employee_active_agents,
    employee_kpi_success_rate,
    goal_decompositions_total,
    goal_decomposition_duration_seconds,
    goal_tasks_generated,
    task_execution_total,
    task_execution_duration_seconds,
    task_queue_depth,
    task_dependencies_resolved,
)

from .tracing import (
    init_tracing,
    get_tracer,
    shutdown_tracing,
    SpanAttributes,
    trace_ai_operation,
    trace_agent_task,
    trace_goal_decomposition,
    trace_task_execution,
    trace_operation,
    inject_trace_context,
    extract_trace_context,
    TracedOperation,
)

__all__ = [
    # Logging
    "get_correlation_id",
    "set_correlation_id",
    "correlation_context",
    "request_context",
    "configure_logging",
    "get_logger",
    "get_structured_logger",
    "log_ai_request",
    "log_ai_response",
    "log_agent_task",
    "log_goal_decomposition",
    # Metrics
    "REGISTRY",
    "get_metrics_registry",
    "generate_metrics",
    "track_http_request",
    "track_provider_request",
    "track_provider_error",
    "set_provider_availability",
    "track_agent_task",
    "track_coordination",
    "track_goal_decomposition",
    "track_task_execution",
    "set_queue_depth",
    "set_employee_agents",
    "set_employee_success_rate",
    "TrackProviderRequest",
    "TrackAgentTask",
    "TrackGoalDecomposition",
    # Tracing
    "init_tracing",
    "get_tracer",
    "shutdown_tracing",
    "SpanAttributes",
    "trace_ai_operation",
    "trace_agent_task",
    "trace_goal_decomposition",
    "trace_task_execution",
    "trace_operation",
    "inject_trace_context",
    "extract_trace_context",
    "TracedOperation",
]
