#!/usr/bin/env python3
"""verify_u51_external_anchor.py -- CI gate for the REAL external transparency anchor (U51).

U51 (no single value commits its own history => cheap notarization/inclusion-proof
infeasible): the chain-head notary (inclusion_proof.py) gives every historical
signed head a trustless inclusion proof against the notary's PUBLISHED ROOT, and
transparency_anchor.py commits that root to an "operator-independent" log -- but
that log's key is REGENERATED by the audit process every run, so it is not a true
external anchor. This gate proves the REAL external anchor
('src/kernels/audit/external_anchor.py') actually works -- it is not a no-op. The
trust anchor is an EXTERNAL public key PINNED OUT-OF-BAND (never generated by the
audit process), and the proof format is RFC 6962 (Merkle inclusion proof + signed
tree head). An auditor verifies against the pinned external key WITHOUT trusting
the operator. Fail-closed: tampered root / forged STH signature / missing
external key rejected. It does NOT assert the live HC-01 chain is externally
anchored in production (that integration is the next step, gated on HC-01
stabilisation); it asserts the capability EXISTS and is fail-closed.

Exit 0 = capability verified. Exit 1 = a capability claim failed.
"""
from __future__ import annotations

import json
import sys
import pathlib
import tempfile

REPO = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))  # required by tests/test_guardrail_scripts.py

from src.kernels.audit.dual_signature import (  # noqa: E402
    DEFAULT_SIGN_ALG,
    SIGN_ALGORITHMS,
)
from src.kernels.audit.external_anchor import (  # noqa: E402
    ExternalAnchorReceipt,
    ExternalTransparencyAnchor,
    LocalReferenceLog,
    SignedTreeHead,
)
from src.kernels.audit.inclusion_proof import (  # noqa: E402
    ChainHeadNotary,
    head_digest_of,
)
from src.kernels.audit.root_of_trust import (  # noqa: E402
    ChainRootOfTrust,
    generate_keypair,
)


def _fail(msg: str) -> None:
    print("U51 EXT-ANCHOR GATE FAIL: " + msg)
    sys.exit(1)


def _ref_log():
    # The external log's key is supplied OUT-OF-BAND and pinned (NOT runtime-
    # random) -- this models a third-party log the audit operator does not hold.
    priv, pub = SIGN_ALGORITHMS[DEFAULT_SIGN_ALG].generate_keypair()
    return LocalReferenceLog(log_priv=priv, log_pub=pub), pub


def main() -> int:
    # 1. Compose U51 with the external anchor: notary publishes a root; the
    #    anchor commits it to a log keyed by an out-of-band external key; the
    #    receipt verifies against that pinned key.
    kp = generate_keypair()
    rot = ChainRootOfTrust(private_pem=kp.private_pem, public_pem=kp.public_pem)
    notary = ChainHeadNotary(checkpoint_interval=3)
    for seq in range(5):
        att = rot.sign_head(seq=seq, head_hash="h" * 64, link_hash="l" * 64)
        notary.append_head(head_digest_of(att))
    root = notary.publish_root()
    log, pub = _ref_log()
    anchor = ExternalTransparencyAnchor(
        external_pub_pem=pub, transport=log, self_attested=True
    )
    if anchor.independent:
        _fail("reference log incorrectly reported as independently verified")
    receipt = anchor.publish(root.root_hash)
    ok, reason = anchor.verify_receipt(receipt, root.root_hash)
    if not ok:
        _fail("external anchor receipt failed verification: %s" % reason)

    # 2. Tampered notary root must not verify against the receipt.
    ok, _ = anchor.verify_receipt(receipt, "c" * 64)
    if ok:
        _fail("tampered notary root verified against the external receipt (fail-closed broken)")

    # 3. Forged STH signature must not verify.
    forged = ExternalAnchorReceipt(
        index=receipt.index,
        proof=receipt.proof,
        sth=SignedTreeHead(
            tree_size=receipt.sth.tree_size,
            root_hash=receipt.sth.root_hash,
            timestamp=receipt.sth.timestamp,
            sig_alg=receipt.sth.sig_alg,
            key_id=receipt.sth.key_id,
            signature="A" + receipt.sth.signature[1:],
        ),
        self_attested=receipt.self_attested,
    )
    ok, reason = anchor.verify_receipt(forged, root.root_hash)
    if ok:
        _fail("forged STH signature verified (fail-closed broken)")

    # 4. Missing external key must refuse construction (cannot claim independence).
    raised = False
    try:
        ExternalTransparencyAnchor(external_pub_pem=None, transport=log)
    except ValueError:
        raised = True
    if not raised:
        _fail("anchor constructed without a pinned external key (fail-closed broken)")

    # 5. Clean save/load round-trip; a tampered persisted file must be refused.
    clean = ExternalTransparencyAnchor(
        external_pub_pem=pub, transport=log, self_attested=True
    )
    r0 = clean.publish("a" * 64)
    ok, _ = clean.verify_receipt(r0, "a" * 64)
    if not ok:
        _fail("fresh external anchor receipt failed verification")
    tmp = tempfile.NamedTemporaryFile(mode="w", suffix=".jsonl", delete=False)
    tmp.close()
    clean.save(tmp.name)
    loaded = ExternalTransparencyAnchor.load(
        tmp.name, external_pub_pem=pub, transport=log, self_attested=True
    )
    ok, _ = loaded.verify_consistency()
    if not ok:
        _fail("loaded external anchor failed its own consistency check")

    with open(tmp.name, "r", encoding="utf-8") as fh:
        lines = fh.readlines()
    obj = json.loads(lines[0])
    obj["root"] = "z" * 64
    lines[0] = json.dumps(obj) + "\n"
    with open(tmp.name, "w", encoding="utf-8") as fh:
        fh.writelines(lines)
    refused = False
    try:
        ExternalTransparencyAnchor.load(
            tmp.name, external_pub_pem=pub, transport=log, self_attested=True
        )
    except ValueError:
        refused = True
    if not refused:
        _fail("load accepted a tampered external anchor file (fail-closed broken)")

    print(
        "U51 EXT-ANCHOR OK: real external transparency-log anchor verified -- "
        "RFC 6962 Merkle inclusion proof + STH signed by an out-of-band external "
        "key, receipt verifies against the pinned key, tampered root rejected, "
        "forged STH signature rejected, missing external key refused, clean "
        "save/load round-trip, and a tampered persisted file is refused. The "
        "reference log is reported honestly as SELF-ATTESTED (not independently "
        "verified)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
