#!/usr/bin/env python3
"""verify_u51_external_anchor_ceremony.py -- CI gate for the U51 external anchor KEY CEREMONY (U51C).

U51 REAL external anchor (``src/kernels/audit/external_anchor.py``) requires the
trust anchor be PINNED OUT-OF-BAND -- never generated by the audit process.
``verify_u51_external_anchor.py`` proves the capability works but RUNTIME-GENERATES
the reference key, so it does not prove the provisioning workflow. This gate
closes that gap: it proves the audit process can CONSUME a pinned, out-of-band
external key and verify anchored receipts against it using ONLY the public key
(the audit runtime never holds the external private key -- the production
security property).

What it proves (all fail-closed):
  1. The ceremony record exists and is structurally valid; its self-signature
     verifies against the pinned public key (possession-at-ceremony proof).
  2. The pinned public key's key_id is internally consistent (recomputed).
  3. The committed anchored log loads and verifies consistency against the pinned
     public key (public-key-only -- no private key needed at verification time).
  4. The reference log is reported HONESTLY as self-attested (NOT independently
     verified) -- no false independence claim.
  5. A tampered anchored log is refused (fail-closed).
  6. A missing pinned external key is refused by the anchor (fail-closed at the
     ceremony layer).

It does NOT assert the live HC-01 chain is externally anchored in production
(that integration is the next step, gated on HC-01 stabilisation).

Exit 0 = ceremony consumption path verified. Exit 1 = a claim failed.
"""
from __future__ import annotations

import argparse
import base64
import json
import pathlib
import sys
import tempfile

REPO = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))  # required by tests/test_guardrail_scripts.py

from src.kernels.audit.dual_signature import (  # noqa: E402
    DEFAULT_SIGN_ALG,
    SIGN_ALGORITHMS,
    canonical_bytes,
    key_id_of,
)
from src.kernels.audit.external_anchor import (  # noqa: E402
    ExternalLogTransport,
    ExternalTransparencyAnchor,
)


DEFAULT_CEREMONY_DIR = REPO / "config" / "external_anchor"


class _PinnedKeyAuditTransport(ExternalLogTransport):
    """Audit-only transport stub.

    The audit process consuming a pinned external anchor needs NO live transport:
    verification (load + verify_consistency) uses only the pinned public key.
    This stub documents that the consumption path is public-key-only and never
    requires the external private key.
    """


def _fail(msg: str) -> None:
    print("U51 CEREMONY GATE FAIL: " + msg)
    sys.exit(1)


def _load_ceremony(ceremony_dir: pathlib.Path) -> dict:
    record_path = ceremony_dir / "ceremony_record.json"
    if not record_path.exists():
        _fail(
            "ceremony record missing at %s -- the external anchor was never "
            "provisioned by a key ceremony (run ceremony_anchor_key.py)" % record_path
        )
    try:
        record = json.loads(record_path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        _fail("ceremony record unreadable: %s" % exc)
    for field in (
        "ceremony_id",
        "kind",
        "sig_alg",
        "key_id",
        "public_pem",
        "ceremony_at",
        "notes",
        "ceremony_claim_signature",
    ):
        if field not in record:
            _fail("ceremony record missing required field: %s" % field)
    if record["kind"] != "external-anchor-ceremony":
        _fail("ceremony record has wrong kind: %s" % record["kind"])
    if record["sig_alg"] != DEFAULT_SIGN_ALG:
        _fail("ceremony record uses unexpected sig_alg: %s" % record["sig_alg"])
    pub_pem = record["public_pem"].encode("ascii")
    # Self-signature possession proof + tamper-evidence of the pinned key.
    claim = {
        "ceremony_id": record["ceremony_id"],
        "kind": record["kind"],
        "sig_alg": record["sig_alg"],
        "key_id": record["key_id"],
        "public_pem": record["public_pem"],
        "ceremony_at": record["ceremony_at"],
        "notes": record["notes"],
    }
    try:
        sig = base64.b64decode(record["ceremony_claim_signature"])
    except Exception as exc:
        _fail("ceremony claim signature is not valid base64: %s" % exc)
    scheme = SIGN_ALGORITHMS.get(record["sig_alg"])
    if scheme is None:
        _fail("ceremony record sig_alg unknown: %s" % record["sig_alg"])
    if not scheme.verify(pub_pem, canonical_bytes(claim), sig):
        _fail(
            "ceremony self-signature does NOT verify -- the pinned key was "
            "tampered or was never attested by a ceremony"
        )
    # Internal key_id consistency.
    if key_id_of(pub_pem) != record["key_id"]:
        _fail("ceremony key_id does not match the pinned public key")
    return record


def main() -> int:
    ap = argparse.ArgumentParser(description="U51 external anchor key ceremony gate")
    ap.add_argument(
        "--dir",
        default=str(DEFAULT_CEREMONY_DIR),
        help="directory holding the ceremony artifacts",
    )
    args = ap.parse_args()
    ceremony_dir = pathlib.Path(args.dir)

    record = _load_ceremony(ceremony_dir)
    pub_pem = record["public_pem"].encode("ascii")

    anchor_path = ceremony_dir / "anchored_log.jsonl"
    if not anchor_path.exists():
        _fail(
            "anchored log missing at %s -- ceremony did not produce an anchored log"
            % anchor_path
        )

    # 3. Load + verify the anchored log against the pinned public key (public-key-only).
    try:
        anchor = ExternalTransparencyAnchor.load(
            str(anchor_path),
            external_pub_pem=pub_pem,
            transport=_PinnedKeyAuditTransport(),
            self_attested=True,
        )
    except ValueError as exc:
        _fail("anchored log refused to load: %s" % exc)
    ok, reason = anchor.verify_consistency()
    if not ok:
        _fail(
            "anchored log failed consistency against the pinned key: %s" % reason
        )

    # 4. Honest reporting: reference log is self-attested, never "independently verified".
    if anchor.independent:
        _fail("reference log incorrectly reported as independently verified")

    # 5. Tamper-evidence: a tampered anchored log copy is refused.
    tmp = tempfile.NamedTemporaryFile(mode="w", suffix=".jsonl", delete=False)
    tmp.write(anchor_path.read_text(encoding="utf-8"))
    tmp.close()
    lines = pathlib.Path(tmp.name).read_text(encoding="utf-8").splitlines()
    obj = json.loads(lines[0])
    obj["root"] = "f" * 64 if obj.get("root") != "f" * 64 else "e" * 64
    lines[0] = json.dumps(obj)
    pathlib.Path(tmp.name).write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )
    refused = False
    try:
        ExternalTransparencyAnchor.load(
            tmp.name,
            external_pub_pem=pub_pem,
            transport=_PinnedKeyAuditTransport(),
            self_attested=True,
        )
    except ValueError:
        refused = True
    if not refused:
        _fail("load accepted a tampered anchored log (fail-closed broken)")
    pathlib.Path(tmp.name).unlink(missing_ok=True)

    # 6. Missing pinned external key is refused by the anchor.
    raised = False
    try:
        ExternalTransparencyAnchor(
            external_pub_pem=None, transport=_PinnedKeyAuditTransport()
        )
    except ValueError:
        raised = True
    if not raised:
        _fail("anchor accepted a missing pinned external key (fail-closed broken)")

    print(
        "U51 CEREMONY OK: U51 REAL external anchor key ceremony verified -- the "
        "audit process consumes a pinned out-of-band external key and verifies "
        "anchored receipts against it using ONLY the public key (public-key-only "
        "verification, the production security property). Ceremony self-signature "
        "verified (possession-at-ceremony proof), anchored log consistent, "
        "reference log honestly reported as SELF-ATTESTED (not independently "
        "verified), tampered anchored log refused, and a missing pinned external "
        "key is refused."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
