"""External transparency-log anchor for published notary roots (U51 REAL external anchor).

WHY THIS EXISTS (and why it supersedes the local-key stand-in)
------------------------------------------------------------
``transparency_anchor.py`` commits each published notary root to an "operator-
independent" log signed by a key generated FRESH by the audit process every run
(``TransparencyAnchorLog()`` with no key). That is NOT a true external anchor: the
operator who controls the box can regenerate that key and rewrite the log
alongside the notary root. The residual trust the whole U51 notary was built to
remove survives.

This module makes the anchor genuinely EXTERNAL:
  * The trust anchor is an EXTERNAL public key, configured OUT-OF-BAND (a trust
    file / env), NEVER generated by the audit process. The operator cannot
    regenerate it, so it cannot forge the log.
  * The proof format is RFC 6962 (Certificate Transparency): each root is a Merkle
    leaf; the log signs a Signed Tree Head (STH = tree_size + root + timestamp)
    with the external key. An auditor verifies (a) the leaf's Merkle inclusion
    proof against the STH root, and (b) the STH signature against the pinned
    external public key -- WITHOUT trusting the operator.
  * The log transport is pluggable. ``LocalReferenceLog`` is an in-process RFC 6962
    log used for CI/unit tests -- its signing key is provided OUT-OF-BAND and
    pinned (NOT runtime-random), so it models a third-party log the operator does
    not control. Production wires a real external endpoint (a CT-style log,
    OpenTimestamps, or a Bitcoin anchor) behind the SAME ``ExternalLogTransport``
    interface -- only submit/retrieve transport changes; the verification math is
    identical. Per HD-05 discipline, if NO external key is configured the anchor
    REFUSES to claim independence.

Fail-closed: tampered anchored root / forged inclusion proof / STH signature
failure / missing external key => reject.
"""
from __future__ import annotations

import base64
import datetime as _dt
import hashlib
import json
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

from .dual_signature import (
    DEFAULT_SIGN_ALG,
    SIGN_ALGORITHMS,
    canonical_bytes,
    key_id_of,
)


# --------------------------------------------------------------------------- #
# RFC 6962 (Certificate Transparency) Merkle tree -- pure, testable
# --------------------------------------------------------------------------- #
def _leaf_hash(data: bytes) -> bytes:
    return hashlib.sha256(b"\x00" + data).digest()


def _node_hash(left: bytes, right: bytes) -> bytes:
    return hashlib.sha256(b"\x01" + left + right).digest()


def _largest_power_of_two_less_than(n: int) -> int:
    k = 1
    while k * 2 < n:
        k *= 2
    return k


def merkle_root(leaves_data: List[bytes]) -> bytes:
    """RFC 6962 Merkle tree root over a list of raw leaf data blobs."""
    n = len(leaves_data)
    if n == 0:
        raise ValueError("cannot compute Merkle root of an empty tree")
    if n == 1:
        return _leaf_hash(leaves_data[0])
    k = _largest_power_of_two_less_than(n)
    left = merkle_root(leaves_data[:k])
    right = merkle_root(leaves_data[k:])
    return _node_hash(left, right)


def merkle_inclusion_proof(leaves_data: List[bytes], index: int) -> List[bytes]:
    """RFC 6962 inclusion proof: list of sibling subtree-root hashes."""
    n = len(leaves_data)
    if index < 0 or index >= n:
        raise IndexError("leaf index out of range")
    if n == 1:
        return []
    k = _largest_power_of_two_less_than(n)
    if index < k:
        return merkle_inclusion_proof(leaves_data[:k], index) + [
            merkle_root(leaves_data[k:])
        ]
    return merkle_inclusion_proof(leaves_data[k:], index - k) + [
        merkle_root(leaves_data[:k])
    ]


def verify_inclusion_proof(
    leaf_data: bytes,
    index: int,
    proof: List[bytes],
    tree_size: int,
    root: bytes,
) -> Tuple[bool, str]:
    """Verify a leaf's RFC 6962 inclusion proof against ``root`` (fail-closed)."""
    n = tree_size
    if index < 0 or index >= n:
        return False, "leaf index out of tree range"
    computed, ok = _verify_inclusion(leaf_data, index, proof, n)
    if not ok:
        return False, "inclusion proof does not reach the root"
    if computed != root:
        return False, "leaf does not match root"
    return True, "ok"


def _verify_inclusion(
    leaf_data: bytes, index: int, proof: List[bytes], tree_size: int
) -> Tuple[Optional[bytes], bool]:
    """Recursively recompute the tree root from a leaf + proof.

    Returns ``(computed_root, ok)``. Unlike ``verify_inclusion_proof`` it returns
    the recomputed root rather than comparing against a caller-supplied one, so
    intermediate subtree roots are available to parent levels.
    """
    n = tree_size
    if index < 0 or index >= n:
        return None, False
    if n == 1:
        if proof:
            return None, False
        return _leaf_hash(leaf_data), True
    if not proof:
        return None, False
    k = _largest_power_of_two_less_than(n)
    sibling = proof[-1]
    if index < k:
        sub_root, ok = _verify_inclusion(leaf_data, index, proof[:-1], k)
        if not ok:
            return None, False
        return _node_hash(sub_root, sibling), True
    sub_root, ok = _verify_inclusion(leaf_data, index - k, proof[:-1], n - k)
    if not ok:
        return None, False
    return _node_hash(sibling, sub_root), True


# --------------------------------------------------------------------------- #
# Signed Tree Head (RFC 6962 STH, signed by the EXTERNAL log key)
# --------------------------------------------------------------------------- #
@dataclass
class SignedTreeHead:
    tree_size: int
    root_hash: str  # hex of the Merkle root
    timestamp: str  # ISO-8601 UTC
    sig_alg: str
    key_id: str
    signature: str  # base64 (ascii)

    def _payload(self) -> Dict[str, object]:
        return {
            "tree_size": self.tree_size,
            "root_hash": self.root_hash,
            "timestamp": self.timestamp,
        }

    def verify(self, external_pub_pem: bytes) -> Tuple[bool, str]:
        alg = SIGN_ALGORITHMS.get(self.sig_alg)
        if alg is None:
            return False, "unknown sig_alg: %s" % self.sig_alg
        if self.key_id != key_id_of(external_pub_pem):
            return False, "STH key_id does not match the pinned external key"
        ok = alg.verify(
            external_pub_pem,
            canonical_bytes(self._payload()),
            base64.b64decode(self.signature),
        )
        return ok, ("ok" if ok else "STH signature invalid (log key mismatch / forged)")

    def to_record(self) -> dict:
        return {
            "tree_size": self.tree_size,
            "root_hash": self.root_hash,
            "timestamp": self.timestamp,
            "sig_alg": self.sig_alg,
            "key_id": self.key_id,
            "signature": self.signature,
        }

    @classmethod
    def from_record(cls, d: dict) -> "SignedTreeHead":
        return cls(
            tree_size=int(d["tree_size"]),
            root_hash=d["root_hash"],
            timestamp=d["timestamp"],
            sig_alg=d["sig_alg"],
            key_id=d["key_id"],
            signature=d["signature"],
        )


# --------------------------------------------------------------------------- #
# Transport abstraction (pluggable: local reference log / real external endpoint)
# --------------------------------------------------------------------------- #
@dataclass
class AnchorHandle:
    receipt_id: int
    index: int


class ExternalLogTransport:
    """Abstract external log: submit a notary root, retrieve an inclusion proof + STH."""

    def submit_root(self, root_hash_hex: str) -> AnchorHandle:  # pragma: no cover
        raise NotImplementedError

    def get_inclusion_proof(
        self, handle: AnchorHandle
    ) -> Tuple[int, List[str], SignedTreeHead]:  # pragma: no cover
        raise NotImplementedError

    def get_signed_tree_head(self) -> SignedTreeHead:  # pragma: no cover
        raise NotImplementedError


class LocalReferenceLog(ExternalLogTransport):
    """In-process RFC 6962 log used for CI/unit tests.

    Its signing key is provided OUT-OF-BAND and PINNED (NOT runtime-random): the
    caller supplies the private key, modelling a third-party log the audit
    operator does not control. The same ``ExternalLogTransport`` interface is
    implemented by a real external endpoint in production -- only submit/retrieve
    transport changes; verification math is identical.
    """

    def __init__(
        self,
        log_priv: bytes,
        log_pub: bytes,
        sig_alg: str = DEFAULT_SIGN_ALG,
    ):
        self._priv = log_priv
        self._pub = log_pub
        self._sig_alg = sig_alg
        self._key_id = key_id_of(log_pub)
        self._leaves: List[bytes] = []  # raw notary-root-hash bytes

    def submit_root(self, root_hash_hex: str) -> AnchorHandle:
        raw = bytes.fromhex(root_hash_hex)
        idx = len(self._leaves)
        self._leaves.append(raw)
        return AnchorHandle(receipt_id=idx, index=idx)

    def get_inclusion_proof(
        self, handle: AnchorHandle
    ) -> Tuple[int, List[str], SignedTreeHead]:
        proof = [p.hex() for p in merkle_inclusion_proof(self._leaves, handle.index)]
        return handle.index, proof, self._make_sth()

    def get_signed_tree_head(self) -> SignedTreeHead:
        return self._make_sth()

    def _make_sth(self) -> SignedTreeHead:
        root = merkle_root(self._leaves)
        ts = _dt.datetime.now(_dt.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        payload = canonical_bytes(
            {"tree_size": len(self._leaves), "root_hash": root.hex(), "timestamp": ts}
        )
        sig = SIGN_ALGORITHMS[self._sig_alg].sign(self._priv, payload)
        return SignedTreeHead(
            tree_size=len(self._leaves),
            root_hash=root.hex(),
            timestamp=ts,
            sig_alg=self._sig_alg,
            key_id=self._key_id,
            signature=base64.b64encode(sig).decode("ascii"),
        )


# --------------------------------------------------------------------------- #
# External transparency anchor (the auditor-facing capability)
# --------------------------------------------------------------------------- #
@dataclass
class ExternalAnchorReceipt:
    index: int
    proof: List[str]  # hex sibling subtree roots
    sth: SignedTreeHead
    self_attested: bool

    def to_record(self) -> dict:
        return {
            "index": self.index,
            "proof": list(self.proof),
            "sth": self.sth.to_record(),
            "self_attested": self.self_attested,
        }

    @classmethod
    def from_record(cls, d: dict) -> "ExternalAnchorReceipt":
        return cls(
            index=int(d["index"]),
            proof=list(d["proof"]),
            sth=SignedTreeHead.from_record(d["sth"]),
            self_attested=bool(d["self_attested"]),
        )


class ExternalTransparencyAnchor:
    """Anchor published notary roots to an EXTERNAL, out-of-band-keyed log.

    Fail-closed: ``external_pub_pem`` MUST be pinned out-of-band (never generated
    by the audit process) or construction raises. A receipt verifies only if the
    STH signature checks against that pinned key AND the Merkle inclusion proof
    reaches the STH root. ``self_attested`` marks a reference/CI log that is NOT a
    real third-party endpoint -- verification still runs, but the result is
    reported honestly as self-attested, never as "independently verified".
    """

    def __init__(
        self,
        external_pub_pem: bytes,
        transport: ExternalLogTransport,
        self_attested: bool = False,
        sig_alg: str = DEFAULT_SIGN_ALG,
    ):
        if external_pub_pem is None:
            raise ValueError(
                "ExternalTransparencyAnchor requires a pinned EXTERNAL public key "
                "(configured out-of-band) -- it must never be generated by the "
                "audit process"
            )
        self._pub = external_pub_pem
        self._key_id = key_id_of(external_pub_pem)
        self._self_attested = self_attested
        self._sig_alg = sig_alg
        if transport is None:
            raise ValueError(
                "a transport must be provided (LocalReferenceLog for CI, or a real "
                "external endpoint in production)"
            )
        self._transport = transport
        self._anchored: List[Tuple[str, ExternalAnchorReceipt]] = []

    @property
    def independent(self) -> bool:
        """True only when backed by a real (non-self-attested) external log."""
        return not self._self_attested

    @property
    def anchored_roots(self) -> List[str]:
        return [r for r, _ in self._anchored]

    def publish(self, notary_root_hash: str) -> ExternalAnchorReceipt:
        handle = self._transport.submit_root(notary_root_hash)
        index, proof, sth = self._transport.get_inclusion_proof(handle)
        receipt = ExternalAnchorReceipt(
            index=index, proof=proof, sth=sth, self_attested=self._self_attested
        )
        self._anchored.append((notary_root_hash, receipt))
        return receipt

    def verify_receipt(
        self,
        receipt: ExternalAnchorReceipt,
        notary_root_hash: Optional[str] = None,
    ) -> Tuple[bool, str]:
        if notary_root_hash is None:
            return False, "notary_root_hash is required to verify a receipt"
        # 1. STH signature against the pinned external key (operator cannot forge).
        ok, reason = receipt.sth.verify(self._pub)
        if not ok:
            return False, reason
        # 2. Merkle inclusion proof against the STH root (operator cannot drop/
        #    reorder / rewrite the leaf without breaking this).
        try:
            raw = bytes.fromhex(notary_root_hash)
        except ValueError:
            return False, "notary_root_hash is not valid hex"
        ok, reason = verify_inclusion_proof(
            raw,
            receipt.index,
            [bytes.fromhex(p) for p in receipt.proof],
            receipt.sth.tree_size,
            bytes.fromhex(receipt.sth.root_hash),
        )
        if not ok:
            return False, reason
        if self._self_attested:
            return True, "ok (SELF-ATTESTED reference only -- NOT independently verified)"
        return True, "ok (verified against the pinned external log key)"

    def verify_consistency(self) -> Tuple[bool, str]:
        for root_hex, receipt in self._anchored:
            ok, reason = self.verify_receipt(receipt, root_hex)
            if not ok:
                return False, reason
        return True, "ok (%d anchored roots)" % len(self._anchored)

    # -- persistence (fail-closed) ---------------------------------------- #
    def save(self, path: str) -> None:
        ok, reason = self.verify_consistency()
        if not ok:
            raise ValueError("refusing to save an inconsistent external anchor: %s" % reason)
        with open(path, "w", encoding="utf-8") as fh:
            for root_hex, receipt in self._anchored:
                fh.write(
                    json.dumps({"t": "extanchor", "root": root_hex, **receipt.to_record()})
                    + "\n"
                )

    @classmethod
    def load(
        cls,
        path: str,
        external_pub_pem: bytes,
        transport: ExternalLogTransport,
        self_attested: bool = False,
        sig_alg: str = DEFAULT_SIGN_ALG,
    ) -> "ExternalTransparencyAnchor":
        anchor = cls(
            external_pub_pem=external_pub_pem,
            transport=transport,
            self_attested=self_attested,
            sig_alg=sig_alg,
        )
        with open(path, "r", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                obj = json.loads(line)
                if obj.get("t") != "extanchor":
                    continue
                receipt = ExternalAnchorReceipt.from_record(obj)
                anchor._anchored.append((obj["root"], receipt))
        ok, reason = anchor.verify_consistency()
        if not ok:
            raise ValueError("refusing to load a tampered external anchor: %s" % reason)
        return anchor
